[cartridge]
publisher_id = 0x00
game_id = 0
game_version = 0

save_type = "SRAM_512KB"
color = false
rtc = false
vertical = false

# mapper = "2003"
# rom_speed = 1
# rom_bus_width = 16
rom_banks = 256
# rom_last_bank = 127

rom_reserve_bootrom_area = true
