baseURL = 'http://docs.asie.pl/swanshell'
languageCode = 'en-us'
title = 'swanshell documentation'
theme = 'hugo-geekdoc'

pluralizeListTitles = false

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode or when nesting shortcodes (e.g. img within
    # columns or tabs)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[goldmark]
  [Extensions]
    footnote = true

[taxonomies]
   tag = "tags"

[params]  
  geekdocLogo = "logo.png"
