name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: cbrzeszczot/wonderful:wswan-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch missing submodules
        run: git config --global --add safe.directory `pwd` && git submodule update --init --recursive

      - name: Install additional dependencies
        run: apt-get update && apt-get install -y pipx python3 python3-pil && pipx install uv && wf-pacman -Syu --noconfirm && wf-pacman -Su --noconfirm wf-tools wf-superfamiconv wf-zx0-salvador

      - name: Configure PATH
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Build
        run: make dist

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: swanshell
          path: dist/*
